import logging
from db_manager import DBManager
from llm_engine import LLMEngine

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


class DialogueManager:
    def __init__(self):
        logging.info("Initializing DialogueManager")
        self.db_manager = DBManager()
        self.llm_engine = LLMEngine()


    def close(self):
        """
        Close resources used by the DialogueManager.
        """
        self.db_manager.close()

    def handle_dialogue(self, player_input, scene_id):
        logging.info(f"Handling dialogue for scene ID: {scene_id} with player input: {player_input}")
        # Retrieve scene description and NPCs for the current scene
        description, npcs = self.db_manager.get_scene_by_id(scene_id)
        
        # Format prompt with scene description, NPC context, and player input
        prompt = f'''Scene description: {description}. NPCs present: {', '.join(npcs) if npcs else 'None'}. Player says: {player_input}. Respond as one of the NPCs if possible or describe the environment. Response in format [npc_name]: Dialouge '''
           
        
        # Generate response from LLM
        npc_response = self.llm_engine.generate_response(prompt)
        
        return npc_response.replace(prompt, '')

    def generate_enhanced_description(self, basic_description):
        """
        Use LLM to expand a basic scene description into a more vivid, detailed prompt.
        
        Args:
            basic_description (str): Basic scene description.
        
        Returns:
            str: Enhanced description generated by the LLM.
        """
        # Prompt the LLM to expand the basic description

        prompt_str = 'Act as a professional prompt engineer. Write a prompt for Stable diffusion XL model, text to image generation. The prompt should be not more than 70 tokens. Use the following text as base description of the scene:'
        prompt = f"{prompt_str} {basic_description}"
        
        
        # Generate the enhanced description
        enhanced_description = self.llm_engine.generate_response(prompt)
        
        return enhanced_description.replace(prompt, '')

    def check_scene_transition_conditions(self, player_input, current_scene_id):
        """
        Determine if player input should trigger a scene transition.
        
        Args:
            player_input (str): The input provided by the player.
            current_scene_id (int): The ID of the current scene.
        
        Returns:
            int or None: The ID of the next scene if a transition is triggered, otherwise None.
        """
        # Check for keywords in player input to determine if a transition should occur
        if "next" in player_input.lower() or "continue" in player_input.lower():
            # Retrieve the next possible scenes from the current scene
            next_scene_options = self.db_manager.get_next_scene_options(current_scene_id)
            if next_scene_options:
                # For now, automatically transition to the first available next scene
                return next_scene_options[0]["id"]
        return None