prompts = [
    "An image of {} reading a book under soft evening light, highly detailed, close-up shot, in a cozy room.",
    "An image of {} sitting in a coffee shop, warm lighting, realistic, medium shot, with cityscape in the background.",
    "An image of {} walking through a forest, dappled sunlight filtering through trees, cinematic, wide shot, lush greenery around.",
    "An image of {} painting on a canvas, soft morning light, highly detailed, close-up, in a studio with art supplies.",
    "An image of {} running along the beach, golden hour lighting, realistic, medium shot, with waves in the background.",
    "An image of {} climbing a mountain, dramatic lighting, dynamic, wide shot, rocky terrain around.",
    "An image of {} meditating in a peaceful garden, soft natural lighting, highly detailed, portrait shot, flowers in the background.",
    "An image of {} playing a guitar by a campfire, warm firelight, close-up shot, night sky and stars visible.",
    "An image of {} cooking in a rustic kitchen, warm and cozy lighting, medium shot, with wooden shelves in the background.",
    "An image of {} riding a bicycle through the city, bright daylight, realistic, dynamic shot, urban environment around.",
    "An image of {} relaxing on a hammock, soft afternoon light, close-up shot, tropical background with palm trees.",
    "An image of {} sitting by a lake, golden hour lighting, highly detailed, medium shot, mountains reflecting in the water.",
    "An image of {} hiking on a scenic trail, sunlight filtering through clouds, wide shot, with a vast landscape view.",
    "An image of {} working on a laptop in a cafe, soft indoor lighting, realistic, medium shot, with coffee cup in the background.",
    "An image of {} practicing yoga on a beach, sunset lighting, wide shot, waves rolling in the background.",
    "An image of {} in a snowy forest, cool blue lighting, highly detailed, close-up shot, snowflakes around.",
    "An image of {} feeding birds in a park, soft morning light, realistic, medium shot, with greenery and trees.",
    "An image of {} reading a map in a city, bright midday lighting, medium shot, busy street in the background.",
    "An image of {} swimming underwater, natural sunlight filtering through, close-up shot, detailed bubbles around.",
    "An image of {} looking through a telescope, moonlit night, close-up shot, starry sky in the background.",
    "An image of {} dancing in a field, golden sunset lighting, wide shot, with flowers swaying in the breeze.",
    "An image of {} holding a lantern in a dark forest, eerie lighting, highly detailed, close-up shot, misty background.",
    "An image of {} drawing on a sketchpad, soft indoor lighting, medium shot, art supplies scattered around.",
    "An image of {} riding a horse on a trail, bright natural lighting, wide shot, mountains in the background.",
    "An image of {} looking out a rainy window, soft ambient lighting, close-up shot, raindrops on the glass.",
    "An image of {} working in a high-tech lab, cool fluorescent lighting, medium shot, futuristic background.",
    "An image of {} sitting on a city rooftop, sunset glow, wide shot, urban skyline in the background.",
    "An image of {} reading under a tree, soft afternoon light, close-up shot, leaves casting shadows.",
    "An image of {} enjoying a picnic by the river, natural sunlight, medium shot, with scenic landscape.",
    "An image of {} sketching in a museum, soft ambient lighting, realistic, close-up shot, art in the background.",
    "An image of {} fishing by a lake at dawn, misty early morning light, wide shot, tranquil water.",
    "An image of {} playing chess in a park, gentle sunlight, medium shot, trees and benches around.",
    "An image of {} sitting on a train, warm lighting from windows, close-up shot, countryside outside.",
    "An image of {} painting a mural on a wall, bright outdoor lighting, wide shot, urban street setting.",
    "An image of {} running through a meadow, sunrise glow, dynamic shot, flowers and grass around.",
    "An image of {} gardening in a backyard, natural daylight, realistic, medium shot, with plants and soil.",
    "An image of {} studying in a library, soft indoor lighting, close-up shot, bookshelves in the background.",
    "An image of {} playing the piano in a dimly lit room, spotlight on hands, medium shot, piano keys in focus.",
    "An image of {} surfing in the ocean, bright natural light, dynamic shot, waves crashing around.",
    "An image of {} riding a motorcycle at dusk, headlight illuminating the road, medium shot, city lights in background.",
    "An image of {} photographing a sunset, golden hour lighting, close-up shot, camera in hands.",
    "An image of {} sitting by a campfire in the woods, warm firelight, close-up shot, dark forest in the background.",
    "An image of {} climbing rocks by a waterfall, bright natural light, dynamic shot, water splashing around.",
    "An image of {} holding an umbrella in the rain, soft ambient lighting, close-up shot, raindrops on umbrella.",
    "An image of {} writing in a journal at a cafe, soft indoor lighting, close-up shot, with coffee and pastries.",
    "An image of {} practicing martial arts outdoors, bright sunlight, dynamic shot, mountains in background.",
    "An image of {} exploring a cave with a flashlight, eerie lighting, medium shot, stalactites around.",
    "An image of {} playing with a pet dog in the yard, warm sunlight, close-up shot, grass and flowers around.",
    "An image of {} watching the sunset on a hilltop, soft evening light, wide shot, panoramic view in background.",
    "An image of {} relaxing on a balcony, sunset lighting, close-up shot, cityscape below.",
    "{} is seen reading a book by soft evening light, highly detailed, close-up view, cozy room setting.",
    "Captured in a coffee shop, {} enjoys a warm ambiance, realistic, medium shot, cityscape seen in the background.",
    "{} walks through a lush forest, sunlight filtering through leaves, cinematic, wide shot, greenery all around.",
    "A detailed view of {} painting on a canvas in soft morning light, close-up, inside an artist’s studio.",
    "{} is running along the beach at golden hour, realistic, medium shot, with waves crashing in the background.",
    "Photograph of {} climbing a rugged mountain, dramatic lighting, wide angle, rocky terrain surrounding.",
    "{} meditates in a peaceful garden, soft natural light enhances the scene, portrait shot, flowers visible nearby.",
    "A nighttime shot of {} playing guitar by a campfire, warm firelight glow, close-up, under the starlit sky.",
    "{} cooks in a rustic kitchen, warm and cozy lighting, medium shot, wooden shelves lining the walls.",
    "{} riding a bicycle down a city street, bright daylight illuminating, dynamic shot, urban environment around.",
    "A tranquil moment of {} relaxing on a hammock, soft afternoon sunlight, close-up, palm trees in background.",
    "{} sits by a serene lake at golden hour, highly detailed, medium shot, with mountain reflections in the water.",
    "{} hikes on a scenic trail, clouds and sunlight combine for dramatic lighting, wide shot, vast landscape view.",
    "{} working on a laptop in a cafe, soft lighting creates a calm atmosphere, medium shot, coffee cup nearby.",
    "On the beach, {} practices yoga under the setting sun, wide shot, with waves rolling onto shore.",
    "{} stands in a snowy forest, cool lighting surrounds, highly detailed, close-up shot, snowflakes gently falling.",
    "{} is seen feeding birds in the park, soft morning light fills the scene, medium shot, surrounded by greenery.",
    "{} looks over a city map, bright midday sunlight illuminates, medium shot, busy street in the background.",
    "Underwater view of {}, sunlight streaming through, close-up, with detailed bubbles rising around.",
    "{} peers through a telescope at night, moonlit scene, close-up, with a star-filled sky overhead.",
    "{} dances in a field of flowers, golden sunset lighting, wide shot, petals and grasses around swaying.",
    "{} holding a lantern in a shadowy forest, mysterious lighting, close-up, misty trees visible behind.",
    "{} sketches on a pad in soft indoor lighting, medium shot, with art supplies scattered nearby.",
    "{} rides a horse along a mountain trail, bright daylight, wide shot, breathtaking scenery in background.",
    "{} gazes out a rainy window, soft ambient light, close-up view, raindrops on glass in focus.",
    "{} working in a high-tech lab, fluorescent lighting casts cool tones, medium shot, futuristic setting around.",
    "{} sits on a rooftop with a sunset glow, wide shot, urban skyline stretching into the distance.",
    "{} reads under a tree, late afternoon light creating shadows, close-up, with leaves gently rustling around.",
    "A picnic by the river with {}, natural sunlight illuminating, medium shot, scenic landscape beyond.",
    "{} sketching in a museum, ambient lighting, close-up shot, with famous artworks visible in the background.",
    "{} fishing at dawn by a lake, misty early light, wide shot, calm water reflecting the surroundings.",
    "{} playing chess in a park, gentle sunlight overhead, medium shot, trees providing a serene backdrop.",
    "{} sitting on a train, soft window lighting casts a warm glow, close-up, countryside visible outside.",
    "{} paints a mural on an outdoor wall, bright sunlight, wide shot, with urban street setting around.",
    "{} running through a meadow at sunrise, glowing light, dynamic shot, flowers and grasses beneath.",
    "{} gardening in the backyard, bright natural daylight, medium shot, surrounded by green plants and soil.",
    "{} studying in a quiet library, indoor lighting softly illuminating, close-up shot, bookshelves nearby.",
    "{} playing piano in a dim room, spotlight on hands, medium shot, piano keys in sharp focus.",
    "{} surfing in the ocean, bright natural light, dynamic shot, waves crashing dramatically.",
    "{} riding a motorcycle at dusk, headlight casting light on road, medium shot, city lights in the distance.",
    "{} capturing a sunset on camera, golden hour lighting, close-up, the camera lens in sharp focus.",
    "{} by a campfire in the woods, warm firelight, close-up shot, trees silhouetted in the background.",
    "{} scaling rocks near a waterfall, bright natural light, dynamic shot, water splashing around.",
    "{} holding an umbrella in the rain, soft ambient light, close-up view, raindrops trickling down.",
    "{} journaling in a cafe, cozy lighting, close-up shot, with coffee and pastries in sight.",
    "{} practicing martial arts outdoors, sunlight illuminating, dynamic shot, mountains standing in background.",
    "{} exploring a dark cave with a flashlight, eerie lighting, medium shot, with stalactites all around.",
    "{} playing with a pet dog in the yard, warm sunlight, close-up shot, grass and flowers in bloom.",
    "{} watching a sunset from a hilltop, soft evening light, wide shot, panoramic view of landscape.",
    "{} relaxing on a balcony, sunset casting a golden glow, close-up, cityscape stretching below.",
     "{} standing by a river, gentle evening light, medium shot, trees and water reflecting the sky.",
    "Captured outdoors, {} enjoys a bright sunny day, medium shot, with blue skies and clouds.",
    "{} is seen stargazing from a hilltop, cool night lighting, wide shot, expansive sky above.",
    "At dawn, {} is fishing by a quiet pond, mist hanging low, close-up, calm surroundings.",
    "{} enjoys a swing in the park, soft morning light, close-up, with green trees all around.",
    "{} reading a newspaper on a park bench, gentle afternoon light, medium shot, urban park in background.",
    "A quiet scene of {} drawing by candlelight, warm glow, close-up shot, with soft shadows.",
    "{} skating on an icy lake, bright winter sunlight, wide shot, snowy mountains visible.",
    "{} exploring a dense forest, scattered sunlight, medium shot, lush green foliage everywhere.",
    "{} standing by a waterfall, natural sunlight filtering through, wide shot, with mist rising.",
    "{} in a flower field, gentle breeze, close-up, colorful petals swaying.",
    "Evening shot of {} riding a skateboard, street lights casting glow, urban scene around.",
    "{} by the seaside, ocean breeze, medium shot, with endless blue water stretching out.",
    "Photograph of {} building a sandcastle on the beach, warm sun overhead, close-up, ocean in background.",
    "{} watching planes take off at sunset, airport lights visible, medium shot, sky changing colors.",
    "A winter scene with {} holding a mug of hot chocolate, cozy indoor lighting, close-up, with snow outside.",
    "{} seen studying on a rooftop at dusk, city lights starting to glow, medium shot, urban skyline around.",
    "{} working out at a gym, cool lighting, medium shot, fitness equipment surrounding.",
    "{} playing soccer in a field, bright daylight, action shot, teammates and green grass visible.",
    "{} walking a dog through the park, warm afternoon light, medium shot, trees and open field nearby.",
    "{} kayaking on a lake, bright natural light, wide shot, water and trees in the background.",
    "{} riding a scooter down a busy street, morning light, dynamic shot, with traffic around.",
    "{} resting in a cozy reading nook, soft indoor lighting, close-up, surrounded by books.",
    "{} captured practicing archery outdoors, bright natural light, medium shot, target in the distance.",
    "{} at an outdoor market, warm midday light, medium shot, with various stalls and goods around.",
    "{} climbing a rock wall, sunlight casting strong shadows, action shot, in an indoor climbing gym.",
    "{} cooking over a campfire in the forest, warm firelight, medium shot, trees surrounding.",
    "{} painting a landscape outdoors, sunlight filtering through clouds, wide shot, open nature setting.",
    "{} looking at a map under moonlight, soft cool tones, medium shot, starry sky above.",
    "{} diving into a swimming pool, bright daylight, action shot, with water splashing everywhere.",
    "{} fixing a bike by the roadside, warm afternoon light, close-up, tools and bike parts around.",
    "{} enjoying a bonfire at the beach, warm firelight, wide shot, with friends gathered nearby.",
    "{} rollerblading in a park, bright daylight, action shot, green trees lining the path.",
    "{} relaxing in a treehouse, soft natural lighting, close-up, with branches and leaves visible.",
    "{} doing pottery in a studio, warm indoor lighting, close-up, clay and tools nearby.",
    "{} horseback riding in an open field, sunlight casting a glow, medium shot, with mountains in distance.",
    "{} playing frisbee with friends, bright afternoon light, action shot, green field around.",
    "{} enjoying ice cream on a summer day, soft natural light, close-up, cityscape in background.",
    "{} sitting on a porch swing, gentle evening light, medium shot, garden in the background.",
    "{} playing with sparklers at dusk, warm glow, close-up, with stars faintly visible.",
    "{} taking photos in a botanical garden, soft sunlight filtering through, close-up, flowers in bloom.",
    "{} watching a parade, bright midday sunlight, medium shot, colorful floats passing by.",
    "{} learning to surf, bright sunlight reflecting on waves, action shot, beach and waves in background.",
    "{} setting up a tent in the forest, dappled sunlight, medium shot, surrounded by trees and camping gear.",
    "{} reading by a fireplace, cozy warm lighting, close-up, bookshelves and firewood nearby.",
    "{} at a concert, colorful stage lights, wide shot, with crowd and musicians on stage.",
    "{} playing basketball outdoors, afternoon sun casting shadows, action shot, court and hoop visible.",
    "{} enjoying tea in a garden, soft daylight, close-up, with flowers and greenery around.",
    "{} skateboarding down a ramp, bright natural light, dynamic shot, skatepark setting.",
    "{} practicing calligraphy, warm indoor light, close-up, with paper and ink nearby.",
    "{} enjoying a road trip, bright sunlight, medium shot, car window open and wind blowing.",
    "{} camping in the desert, sunset casting warm tones, wide shot, with sand dunes in the background.",
    "{} reading in a hammock, gentle sunlight through leaves, medium shot, tropical scene around.",
    "{} exploring a historic site, soft ambient light, medium shot, ancient ruins in the background.",
    "{} sipping coffee on a balcony, morning light, close-up, city view stretching below.",
    "{} harvesting vegetables in a garden, warm sunlight, close-up, plants and soil visible.",
    "{} participating in a pottery class, indoor lighting, medium shot, with clay and tools around.",
    "{} flying a kite in an open field, bright sky, wide shot, with hills in the distance.",
    "{} at a farmers market, warm natural light, medium shot, with fresh produce and vendors around.",
    "{} captured stargazing in a dark field, cool moonlight, wide shot, starry sky stretching above.",
    "{} enjoying breakfast on a terrace, soft morning light, close-up, with food and landscape visible.",
    "{} building a snowman in a snowy park, cool daylight, close-up, with snow all around.",
    "{} captured reading by a lake at sunrise, golden light reflecting, medium shot, calm water visible.",
    "{} sketching a mountain view, bright daylight, medium shot, with rugged landscape in background.",
    "{} playing with a puppy in a grassy field, warm sunlight, close-up, green grass and flowers around.",
    "{} taking photos of a sunrise, golden light, close-up, with camera in focus.",
    "{} building a wooden model, warm workshop lighting, close-up, with tools and wood shavings around.",
    "{} watching the sunset on a hill, soft evening glow, medium shot, panoramic landscape in view.",
    "{} photographing city lights at night, cool tones, close-up, with skyline in background.",
    "{} practicing knitting by a window, soft afternoon light, close-up, yarn and needles in hands.",
    "{} taking a dance class, bright indoor lighting, medium shot, with mirrors and dance floor around.",
    "{} working with a microscope in a lab, cool fluorescent lighting, close-up, scientific equipment visible.",
    "{} enjoying a boat ride on a lake, warm sunlight, medium shot, with water and mountains around.",
    "{} playing volleyball on the beach, golden evening light, action shot, sand and net visible.",
    "{} taking notes in a lecture hall, bright indoor lighting, medium shot, books and laptop nearby.",
    "{} watering plants in a greenhouse, soft sunlight, medium shot, with green plants surrounding.",
    "{} preparing a painting palette, warm studio lighting, close-up, brushes and paints around.",
    "{} riding a ferris wheel, sunset casting colors, medium shot, view stretching into the distance.",
    "{} looking through vintage records, soft indoor lighting, close-up, with record store shelves.",
    "{} rock climbing outdoors, bright sunlight, action shot, rugged cliff in background.",
    "{} riding in a hot air balloon, sunrise glow, wide shot, with landscape below.",
    "{} playing badminton with friends, natural daylight, action shot, green field around.",
    "{} relaxing on a mountain cabin porch, soft morning light, medium shot, forest in background.",
    "{} playing chess indoors, cozy lighting, medium shot, with pieces arranged on the board.",
    "{} exploring a science museum, bright indoor light, medium shot, exhibits surrounding.",
    "{} enjoying a rainy day walk, soft ambient light, medium shot, city streets wet from rain.",
    "{} sitting on a pier by the ocean, warm evening light, medium shot, waves lapping below.",
    "{} jogging through a park at sunrise, soft early morning light, medium shot, trees lining the path.",
    "{} knitting a scarf in a cozy room, soft indoor light, close-up, yarn and needles in focus.",
    "{} lying in a field watching clouds, bright daylight, wide shot, with flowers and grass around.",
    "{} tasting food samples at a market, warm natural lighting, medium shot, fresh produce visible.",
    "{} painting with watercolors by a window, gentle sunlight, close-up, paint and brushes arranged nearby.",
    "{} sitting by a bonfire at night, warm firelight glow, medium shot, surrounded by friends and forest.",
    "{} studying the stars from a quiet hilltop, cool evening tones, wide shot, vast night sky above.",
    "{} taking a walk through autumn leaves, soft afternoon light, medium shot, colorful foliage around.",
    "{} playing a violin on a city street, warm streetlights illuminating, close-up, with buildings in background.",
    "{} relaxing on a boat at sunset, gentle light reflecting off the water, medium shot, horizon stretching out.",
    "{} building a model airplane indoors, cozy lighting, close-up, with tools and parts on the table.",
    "{} practicing ballet in a studio, bright indoor light, medium shot, with mirrors and barre in the background.",
    "{} painting a scenic landscape outdoors, sunlight casting a warm glow, medium shot, with mountains visible in the distance."
]
